apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
 name: nodejs-pipelinerun4 # The name of the pipeline.
spec:
  serviceAccountName: tkn-sa # The service account to access your DockerHub account.
  pipelineRef:
    name: nodejs-pipeline4 # References the pipeline used in this PipelineRun.
  podTemplate:
    securityContext:
      fsGroup: 65532 # non-root UID 65532, which allows the git-clone task command.
  params:
    - name: IMAGE
      value: vigneshvicky12345/maven # The image name as a parameter in nodejs-pipeline.
    - name: TAG
      value: latest
  workspaces:
    - name: node-workspace # The workspace used in the pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi # Amount of storage used
